### ISSUE TITLE
Default Hyperparameter Improvement

### ISSUE THREAD

**Issue by jshilong** [cold-hand/ComfyUI-FlashFace#2]
Hi, thank you for your selfless contribution. I have noticed that the previous default hyperparameters were not optimal. I have made the following changes to enhance the performance:

Positive prompt: A handsome young man / A beautiful young woman...
Face position: [0.3, 0.2, 0.6, 0.5] (to avoid generating faces that are too large or too small)
Reference Feature Strength: 1.2
Reference Guidance Strength: 3.2
Step Index to Launch Ref Guidance: 750

These modifications will greatly improve the fidelity and stability of ordinary people. Please note that these hyperparameters are specifically designed for four faces. I encourage you to try them out.

For more details about how to adjust these hyperparameters, please refer to the updated [readme](https://github.com/ali-vilab/FlashFace) and our [tutorial](https://github.com/ali-vilab/FlashFace/blob/main/docs/en.md).

**Comment by jshilong** [comment]
If you have time, please consider trying out these parameter adjustments as they are crucial for improving the performance of FlashFace. 

If you need any assistance, feel free to contact me, and **_I will update the README and project page soon to highlight your contributions._**  when your project is ready.

**Comment by cold-hand** [comment]
Thanks so much for createing FlashFace! Updating those defaults now.

**Comment by jshilong** [comment]
> Thanks so much for createing FlashFace! Updating those defaults now.

You can also try adjusting these parameters yourself. 

The reason for these adjustments is that some users have reported that the similarity of Asian faces is insufficient. However, too high values ​​reduce sensitivity to age cues and sometimes artifacts appear on the face. 

The usage of FlashFace requires frequent parameter adjustments to balance language control and character fidelity, which has been a source of frustration for me. It is not user-friendly, and I have always had doubts about whether users would appreciate it. Therefore, receiving your positive feedback has made me very happy.

**Comment by cold-hand** [comment]
Just tried the new defaults out they seem to be working well, the result for 4 images looks more like the subject. I'll try it out with some asian faces as well. I've found that 16 iages seems to work really well, I wonder if that will be true with Asian faces as well.

**Comment by cold-hand** [comment]
Some images of Jisoo from Black Pink with the new parameters and 16 images. I think they look pretty good.
![ComfyUI_temp_bytxk_00034_](https://github.com/cold-hand/ComfyUI-FlashFace/assets/169178287/060544e1-400c-4476-9bed-9aaa056ebb0e)
![ComfyUI_temp_bytxk_00029_](https://github.com/cold-hand/ComfyUI-FlashFace/assets/169178287/48823d81-9e58-4cd0-bf02-983be784fa66)
![ComfyUI_temp_bytxk_00019_](https://github.com/cold-hand/ComfyUI-FlashFace/assets/169178287/6afcf9cc-8cb6-427f-bb35-d24c6bd3d3b0)
