### ISSUE TITLE
guidance typo causing cache value setting and getting inconsistent

### ISSUE THREAD

**Issue by chaiyuntian** [cold-hand/ComfyUI-FlashFace#20]
`guidance` vs `guidence`

**The set action of the share_cache values**
The right spelling for guidance here https://github.com/cold-hand/ComfyUI-FlashFace/blob/d32554e0295f9c98ed0b5b4e9066d1224d355952/nodes/flashface_generator.py#L118
`model.share_cache['lamda_feat_before_ref_guidance'] = torch.tensor(lamda_feat_before_ref_guidence).cuda()`
`model.share_cache['step_to_launch_face_guidance'] = step_to_launch_face_guidance`

While the code from orginal FlashFace repo has a typo for guidance in  `lamda_feat_before_ref_guidence` and `step_to_launch_face_guidence`
Code here https://github.com/cold-hand/ComfyUI-FlashFace/blob/d32554e0295f9c98ed0b5b4e9066d1224d355952/flashface/all_finetune/ops/context_diffusion.py#L59

**Getting the share_cache values**
`step_to_launch_face_guidence = model.share_cache.get(
            'step_to_launch_face_guidence', 600)`
`model.share_cache['similarity'] = model.share_cache.get(
                'lamda_feat_before_ref_guidence', 0.85)`

**Comment by cold-hand** [comment]
Thanks! Fixing this now.

**Comment by cold-hand** [comment]
Fixed.

**Comment by chaiyuntian** [comment]
> Fixed.

Great! Thank you so much!
