### ISSUE TITLE
support for batch images?

### ISSUE THREAD

**Issue by GraftingRayman** [cold-hand/ComfyUI-FlashFace#4]
please check this code and see if you want to implement, this supports batch image input

import copy
import random

import numpy as np
import torch
import torch.cuda.amp as amp
import torchvision.transforms as T
import torchvision.transforms.functional as F
from PIL import ImageOps, ImageSequence
from PIL import Image, ImageDraw

from ..flashface.all_finetune.config import cfg
from ..flashface.all_finetune.utils import Compose, PadToSquare, seed_everything, get_padding
from ..ldm.models.retinaface import crop_face, retinaface
import comfy.samplers

padding_to_square = PadToSquare(224)

retinaface_transforms = T.Compose([PadToSquare(size=640), T.ToTensor()])

retinaface = retinaface(pretrained=True, device='cuda').eval().requires_grad_(False)

class FlashFaceDetectFace:
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "images": ("IMAGE",),
            },
        }
    RETURN_TYPES = ("PIL_IMAGE", )
    FUNCTION = "detect_face"
    CATEGORY = "FlashFace"

    def detect_face(self, **kwargs):
        images = kwargs.get('images')
        if not isinstance(images, torch.Tensor) or images.dim() != 4:
            raise ValueError("Input should be a list of images")
        
        pil_imgs = []
        # convert each image in the batch to PIL and append to list
        for img in images:
            img = img.squeeze(0)
            img = img.permute(2, 0, 1)
            pil_image = F.to_pil_image(img)
            pil_imgs.append(pil_image)

        b = len(pil_imgs)
        vis_pil_imgs = copy.deepcopy(pil_imgs)

        # detection
        imgs = torch.stack([retinaface_transforms(u) for u in pil_imgs]).to('cuda')
        boxes, kpts = retinaface.detect(imgs, min_thr=0.6)

        # undo padding and scaling
        face_imgs = []

        for i in range(b):
            # params
            scale = 640 / max(pil_imgs[i].size)
            left, top, _, _ = get_padding(round(scale * pil_imgs[i].width),
                                          round(scale * pil_imgs[i].height), 640)

            # undo padding
            boxes[i][:, [0, 2]] -= left
            boxes[i][:, [1, 3]] -= top
            kpts[i][:, :, 0] -= left
            kpts[i][:, :, 1] -= top

            # undo scaling
            boxes[i][:, :4] /= scale
            kpts[i][:, :, :2] /= scale

            # crop faces
            crops = crop_face(pil_imgs[i], boxes[i], kpts[i])
            if len(crops) != 1:
                raise ValueError(
                    f'Found {len(crops)} faces in the image {i + 1}, please ensure there is only one face in each image'
                )

            face_imgs += crops

            # draw boxes on the pil image
            draw = ImageDraw.Draw(vis_pil_imgs[i])
            for box in boxes[i]:
                box = box[:4].tolist()
                box = [int(x) for x in box]
                draw.rectangle(box, outline='red', width=4)

        return (face_imgs, )

**Comment by 3blackbar** [comment]
Hey does it work ? its a new node for this repo ?

**Comment by GraftingRayman** [comment]
The above code? yes, been using it all day to load batches of images rather than load them individually

What would be nice is masks and a model passthrough so can be used with multi person generation

**Comment by 3blackbar** [comment]
Ok man so ill add it to my folder, its what i was trying to do on my own but XP coding isnt as high .
What do you think can we swap vae to better one ?

**Comment by GraftingRayman** [comment]
I am sure it can be possible

I am messing with it on the fork, adding mask support and model passthrough, taking a bit of time as new to coding myself

**Comment by 3blackbar** [comment]
Great, i tried to add resolution input box to generation node but it kept generating face in the corner so i passed , it can do 1024 no problem, also face detect is default 512 , it can be 1024 too

**Comment by GraftingRayman** [comment]
Yeah a resolution input would be a must

**Comment by 3blackbar** [comment]
Can you turn this into batch from folder ?

**Comment by GraftingRayman** [comment]
I just got resolution working

![image](https://github.com/cold-hand/ComfyUI-FlashFace/assets/156515434/d40f6b8a-2730-4fe4-9606-b884b379e8f1)

Thats a 1024x1024 image generation

**Comment by GraftingRayman** [comment]
yeah, this is a batch from a folder, i use Load Image Batch from DIR (Inspire) node as in the photo above

**Comment by 3blackbar** [comment]
That is fantastic! the only thing i see that id like to change is that damn sampler, it needs like 50 steps to produce good result, but other ones can do fine with 20 steps

**Comment by 3blackbar** [comment]
Ok there is a bug sometimes where i finds more than 1 face in the iamge where there is not, can you force it to ignore it and just use 1st face ?

got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! Found 4 faces in the image 1, please ensure there is only one face in each image
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI-FlashFace\nodes\flashface_detectface.py", line 77, in detect_face
    raise ValueError(
ValueError: Found 4 faces in the image 1, please ensure there is only one face in each image

**Comment by GraftingRayman** [comment]
I will update the repo with the resolution now

I noticed that with the face detecting blurred faces, there is another face there, the detection is highly sensitive

Will need cold-hand to fix

**Comment by cold-hand** [comment]
@GraftingRayman Can you put in a pull request with batch image update and one with the change you made for the resolution?

**Comment by cold-hand** [comment]
> I will update the repo with the resolution now
> 
> I noticed that with the face detecting blurred faces, there is another face there, the detection is highly sensitive
> 
> Will need cold-hand to fix

I'll look into that, the original repo says the image should only have one face or it will cause issues, but there may be a way to get it to select the most prominent face.

**Comment by cold-hand** [comment]
> That is fantastic! the only thing i see that id like to change is that damn sampler, it needs like 50 steps to produce good result, but other ones can do fine with 20 steps I git pulled your repo, works great btw absolute best likeness is possible with x1 y1 on 0.1 and x2 y2 on 0.9

@3blackbar Been trying to add implementations of other samplers with no luck yet, I tried euler and dpm2m++ but got only noise as output, I'll create a new ticket for it because something other than ddim would be great.

**Comment by GraftingRayman** [comment]
> @GraftingRayman Can you put in a pull request with batch image update and one with the change you made for the resolution?

done

**Comment by cold-hand** [comment]
@3blackbar good idea, i'll reacch out, I am getting a bit closer with euler no longer just random noise.


![ComfyUI_temp_zntnk_00003_](https://github.com/cold-hand/ComfyUI-FlashFace/assets/169178287/38a1c681-61ad-42a9-bd9f-7ff565d728c0)

**Comment by 3blackbar** [comment]
IS it me or batch resizes all images to be the same? i get stretched weird faces with it

**Comment by cold-hand** [comment]
> IS it me or batch resizes all images to be the same? i get stretched weird faces with it

I'll check that out,I mostly use image lists.

**Comment by cold-hand** [comment]
@3blackbar can you share the images you are using and which batch node, my face outputs seem fine when using the Batch Images node.
